apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    provider: tap-overview
    type: mysql
  name: xmysqlinstances.overview.tap.vmware.com
spec:
  compositeTypeRef:
    apiVersion: overview.tap.vmware.com/v1alpha1
    kind: XMySQLInstance
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  resources:
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Namespace
        providerConfigRef:
          name: bitnami-services-provider-kubernetes
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      type: FromCompositeFieldPath
  - base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      spec:
        forProvider:
          chart:
            name: mysql
            repository: https://charts.bitnami.com/bitnami
            version: 9.5.0
          namespace: ""
          set:
          - name: fullnameOverride
            valueFrom:
              secretKeyRef:
                key: host
                namespace: ""
          - name: primary.service.ports.mysql
            valueFrom:
              secretKeyRef:
                key: port
                namespace: ""
          - name: auth.username
            valueFrom:
              secretKeyRef:
                key: username
                namespace: ""
          - name: auth.database
            valueFrom:
              secretKeyRef:
                key: database
                namespace: ""
          values:
            primary:
              persistence:
                size: 1
              extraFlags: "--max_connections=500"

        providerConfigRef:
          name: bitnami-services-provider-helm
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.set[0].valueFrom.secretKeyRef.namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.set[1].valueFrom.secretKeyRef.namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.set[2].valueFrom.secretKeyRef.namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.set[3].valueFrom.secretKeyRef.namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.values.auth.existingSecret
      type: FromCompositeFieldPath
    - fromFieldPath: spec.storageGB
      toFieldPath: spec.forProvider.values.primary.persistence.size
      transforms:
      - string:
          fmt: '%dGi'
          type: Format
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.set[0].valueFrom.secretKeyRef.name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.set[1].valueFrom.secretKeyRef.name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.set[2].valueFrom.secretKeyRef.name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.set[3].valueFrom.secretKeyRef.name
      type: FromCompositeFieldPath
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        connectionDetails:
        - apiVersion: v1
          fieldPath: data.provider
          kind: Secret
          namespace: ""
          toConnectionSecretKey: provider
        - apiVersion: v1
          fieldPath: data.type
          kind: Secret
          namespace: ""
          toConnectionSecretKey: type
        - apiVersion: v1
          fieldPath: spec.clusterIP
          kind: Service
          namespace: ""
          toConnectionSecretKey: host
        - apiVersion: v1
          fieldPath: data.port
          kind: Secret
          namespace: ""
          toConnectionSecretKey: port
        - apiVersion: v1
          fieldPath: data.database
          kind: Secret
          namespace: ""
          toConnectionSecretKey: database
        - apiVersion: v1
          fieldPath: data.username
          kind: Secret
          namespace: ""
          toConnectionSecretKey: username
        - apiVersion: v1
          fieldPath: data.mysql-password
          kind: Secret
          namespace: ""
          toConnectionSecretKey: password
        forProvider:
          manifest:
            apiVersion: secretgen.k14s.io/v1alpha1
            kind: Password
            metadata:
              namespace: ""
            spec:
              length: 32
              secretTemplate:
                stringData:
                  mysql-password: $(value)
                  mysql-root-password: $(value)
                  port: "3306"
                  provider: bitnami
                  type: mysql
                  username: mysql
                type: connection.crossplane.io/v1alpha1
        providerConfigRef:
          name: bitnami-services-provider-kubernetes
        writeConnectionSecretToRef:
          namespace: crossplane-system
    connectionDetails:
    - fromConnectionSecretKey: provider
    - fromConnectionSecretKey: type
    - fromConnectionSecretKey: host
    - fromConnectionSecretKey: port
    - fromConnectionSecretKey: database
    - fromConnectionSecretKey: username
    - fromConnectionSecretKey: password
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[0].namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[1].namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[2].namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[3].namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[4].namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[5].namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[6].namespace
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.spec.secretTemplate.stringData.database
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.spec.secretTemplate.stringData.host
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-mysql'
          type: Format
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[0].name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[1].name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[2].name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[3].name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[4].name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[5].name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.name
      toFieldPath: spec.connectionDetails[6].name
      type: FromCompositeFieldPath
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmysqlinstances.overview.tap.vmware.com
spec:
  connectionSecretKeys:
  - provider
  - type
  - host
  - port
  - database
  - username
  - password
  group: overview.tap.vmware.com
  names:
    kind: XMySQLInstance
    plural: xmysqlinstances
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The OpenAPIV3Schema of this Composite Resource Definition.
            properties:
              storageGB:
                default: 1
                description: The desired storage capacity of the database, in Gigabytes.
                type: integer
            type: object
        type: object
    served: true
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: mysql-high-connection
spec:
  description:
    short: MySQL Config for High Connection Counts
  provisioner:
    crossplane:
      compositeResourceDefinition: xmysqlinstances.overview.tap.vmware.com
      compositionSelector:
        matchLabels:
          provider: tap-overview
          type: mysql
      compositionUpdatePolicy: Manual