---
# Source: prometheus/templates/alertmanager/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "prometheus-alertmanager"
  namespace: prometheus
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: 0.26.0
    helm.sh/chart: prometheus-0.4.3
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/component: alertmanager
data:
  alertmanager.yaml:
    |
      receivers:
        - name: default-receiver
      route:
        group_wait: 10s
        group_interval: 5m
        receiver: default-receiver
        repeat_interval: 3h
---
# Source: prometheus/templates/server/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
  namespace: prometheus
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: 2.47.2
    helm.sh/chart: prometheus-0.4.3
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/component: server
data:
  prometheus.yaml:
    |
      global:
        external_labels:
          monitor: prometheus
      scrape_configs:
        - job_name: prometheus
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                - workloads
          metrics_path: /metrics
          relabel_configs:
            - source_labels:
                - job
              target_label: __tmp_prometheus_job_name
            - action: keep
              source_labels:
                - __meta_kubernetes_service_label_app_kubernetes_io_component
                - __meta_kubernetes_service_labelpresent_app_kubernetes_io_component
              regex: (server);true
            - action: keep
              source_labels:
                - __meta_kubernetes_service_label_app_kubernetes_io_instance
                - __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance
              regex: (prometheus);true
            - action: keep
              source_labels:
                - __meta_kubernetes_service_label_app_kubernetes_io_name
                - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
              regex: (prometheus);true
            - action: keep
              source_labels:
                - __meta_kubernetes_endpoint_port_name
              regex: http
            - source_labels:
                - __meta_kubernetes_endpoint_address_target_kind
                - __meta_kubernetes_endpoint_address_target_name
              separator: ;
              regex: Node;(.*)
              replacement: ${1}
              target_label: node
            - source_labels:
                - __meta_kubernetes_endpoint_address_target_kind
                - __meta_kubernetes_endpoint_address_target_name
              separator: ;
              regex: Pod;(.*)
              replacement: ${1}
              target_label: pod
            - source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - source_labels:
                - __meta_kubernetes_service_name
              target_label: service
            - source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: drop
              source_labels:
                - __meta_kubernetes_pod_phase
              regex: (Failed|Succeeded)
            - source_labels:
                - __meta_kubernetes_service_name
              target_label: job
              replacement: ${1}
            - target_label: endpoint
              replacement: http
            - source_labels:
                - __address__
              target_label: __tmp_hash
              modulus: 1
              action: hashmod
            - source_labels:
                - __tmp_hash
              regex: 0
              action: keep
        - job_name: alertmanager
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                - workloads
          metrics_path: /metrics
          relabel_configs:
            - source_labels:
                - job
              target_label: __tmp_prometheus_job_name
            - action: keep
              source_labels:
                - __meta_kubernetes_service_label_app_kubernetes_io_component
                - __meta_kubernetes_service_labelpresent_app_kubernetes_io_component
              regex: (alertmanager);true
            - action: keep
              source_labels:
                - __meta_kubernetes_service_label_app_kubernetes_io_instance
                - __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance
              regex: (prometheus);true
            - action: keep
              source_labels:
                - __meta_kubernetes_service_label_app_kubernetes_io_name
                - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
              regex: (prometheus);true
            - action: keep
              source_labels:
                - __meta_kubernetes_endpoint_port_name
              regex: http
            - source_labels:
                - __meta_kubernetes_endpoint_address_target_kind
                - __meta_kubernetes_endpoint_address_target_name
              separator: ;
              regex: Node;(.*)
              replacement: ${1}
              target_label: node
            - source_labels:
                - __meta_kubernetes_endpoint_address_target_kind
                - __meta_kubernetes_endpoint_address_target_name
              separator: ;
              regex: Pod;(.*)
              replacement: ${1}
              target_label: pod
            - source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - source_labels:
                - __meta_kubernetes_service_name
              target_label: service
            - source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: drop
              source_labels:
                - __meta_kubernetes_pod_phase
              regex: (Failed|Succeeded)
            - source_labels:
                - __meta_kubernetes_service_name
              target_label: job
              replacement: ${1}
            - target_label: endpoint
              replacement: http
            - source_labels:
                - __address__
              target_label: __tmp_hash
              modulus: 1
              action: hashmod
            - source_labels:
                - __tmp_hash
              regex: 0
              action: keep
      alerting:
        alertmanagers:
          - scheme: HTTP
            static_configs:
              - targets: [ "prometheus-alertmanager.workloads.svc.cluster.local:80" ]
      rule_files:
        - rules.yaml
  rules.yaml:
    '{}'