apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic
spec:
  build:
    env:
    - name: BP_GRADLE_BUILD_FILE
      value: skip
    - name: BP_JVM_VERSION
      value: "17"
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: postgres
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_repository_name
      value: "trp-gitops-spring-petclinic"
    - name: scanning_source_policy
      value: lax-scan-policy
    - name: scanning_image_policy
      value: lax-scan-policy
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic
      ref:
        branch: main
  serviceClaims:
    - name: postgres-db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: petclinic-db